# Generated by Django 4.2.3 on 2023-09-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_new_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="new",
            name="date_created",
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
